[package]
name = "sketcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dssim-core = "3.2.5"
image = "0.24.4"
imgref = "1.9.4"
rgb = "0.8.34"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
